sudo: required

language: generic

services:
  - docker
  
script:
  - docker build -t jupyterhub-k8s .
  - docker images
  - docker tag jupyterhub-k8s $DOCKER_USERNAME/jupyterhub-k8s
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/httpd-shibboleth-sp
  - docker logout
